apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    app: {{ include "server.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "server.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.server.port }}
          env:
            - name: PROMETHEUS_ENABLED
              value: {{ .Values.prometheus.enabled | quote }}
            - name: SERVER_HOSTNAME
              value: {{ .Values.server.hostname | quote }}
            - name: SERVER_PORT
              value: {{ .Values.server.port | quote }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.fullname" . }}-secret
                  key: url
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.fullname" . }}-secret
                  key: dbname
            - name: MONGO_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.fullname" . }}-secret
                  key: collectionname
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.server.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.server.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
