auth:
  enabled: true
  rootUser: mongo
  rootPassword: mongo
  usernames:
    - appuser
  passwords:
    - apppass
  databases:
    - appdb

architecture: standalone

persistence:
  enabled: true
  size: 8Gi
  storageClass: local-path

replicaCount: 2
